name: Test

on:
    push:
        branches:
            - 'develop'
    pull_request:
        branches:
            - 'develop'

jobs:
    Test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: SetupJDK 21
              uses: actions/setup-java@4
              with:
                java-version: '21'

            - name: Setup sbt
              uses: sbt/setup-sbt@v1

            - name: Run tests
              run: sbt test